version: '3.7'

services: 
  web: 
    build:  
      context: .
    
    ports: 
      - "8000:8000"
    volumes:
      - ./pabo:/pabo
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DEBUG=1
    