# Generated by Django 3.1.2 on 2020-12-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ms_Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=75)),
                ('pangkat', models.CharField(max_length=50)),
                ('gol', models.CharField(max_length=10)),
                ('unit_kerja', models.CharField(max_length=30)),
            ],
        ),
    ]
